apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: aceivt
spec:
  source:
    git:
      uri: https://https://github.com/peterajessup/coles-ace-build
      ref: master
  output:
    to:
      kind: ImageStreamTag
      name: 'demoace:v0.96'
  strategy:
    dockerStrategy:
      pullSecret:
        name: ibm-entitlement-key
      dockerfilePath: .
