apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: is2
  namespace: cp4i
spec:
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/cp4i/demoace:v0.96
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
  version: 12.0.2.0-r2
  imagePullSecrets:
    name: default-dockercfg-784vv
  license:
    accept: true
    license: L-KSBM-C87FAW
    use: AppConnectEnterpriseNonProduction
  useCommonServices: true
  enableMetrics: true
  replicas: 1
  service:
    endpointType: https
  designerFlowsOperationMode: disabled
  adminServerSecure: false
  tracing:
    enabled: true
    namespace: cp4i
  logFormat: basic
  configurations: ["mqpolicy", "key.jks", "httpsconf", "scramparms"]
